version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:402320383251:task-definition/stock-service-task-definition:1"
        LoadBalancerInfo:
          ContainerName: "stock-service-container"
          ContainerPort: "8082"
        PlatformVersion: "LATEST"